### PR TITLE
Update pair function to include reverse pairs

### PR DESCRIPTION
**Pull request by Elwood-P**
Update pair function to include reverse pairs. Allows large to small spacing pairs e.g. `px-fl-lg-sm`.

### CODE REVIEW

**Review by domchristie — COMMENTED** [review]
Thanks for this! Is there a simpler way to achieve this? Is sorting necessary?

**Comment by Elwood-P** [comment]
Hi Dom, no problem thanks for your work on the plugin. 

Sorting _I think_ only effects the order of the final css. So not a big thing I guess, but I see an effort was made to sort in the `sizes` function in [spacing.js](https://github.com/domchristie/tailwind-utopia/blob/main/lib/spacing.js) which again I think serves only to give a nice order to the rendered css.

Alternatives without sorting could be (still splits the reversed pairs from the forward just not with such a good order)
```
function pair(array) {
  return array.map((v, i) => array.slice(i + 1).map(w => [v, w])).flat()
    .concat(array.map((v, i) => array.slice(i + 1).map(w => [w, v])).flat())
}
```

Or even this which mixes the reverse pairs in with the forward pairs:
```
function pair (array) {
  return array.map((v, i) => array.slice(i + 1).map(w => [[v, w], [w, v]])).flat(2)
}
```

Test outputs of what each of those methods produces can be seen here:
https://codepen.io/Paul-Littlewood/pen/RwvmVey?editors=0012

**Comment by Elwood-P** [comment]
Hmm, if we do want them sorted maybe its best to sort the whole array. So maybe this:

```
function pair (array) {
  return (array.flatMap((v, i) => array.slice(i + 1).flatMap(w => [[v, w], [w, v]])))
    .sort((a, b) => array.indexOf(a[0]) - array.indexOf(b[0]))
} 
```

Updated options:
https://codepen.io/Paul-Littlewood/pen/RwvmVey?editors=0012

**Comment by domchristie** [comment]
Thanks for your work on this. I don't think we need to be too worried about output order, so my preference would be:

```js
function pair (array) {
  return array.map((v, i) => array.slice(i + 1).map(w => [[v, w], [w, v]])).flat(2)
}
```

as it keeps the number of iterations down.

**Comment by Elwood-P** [comment]
Cool, no problem, updated.

**Comment by domchristie** [comment]
Great, thank you!

**Comment by domchristie** [comment]
Released in v1.1.1

**Pull request merged**
